<a href="https://colab.research.google.com/github/hnrqc/sprint4/blob/main/importando_aws.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
#importando as bibliotecas
import psycopg2
import pandas as pd

In [28]:
## Conectando ao banco SQL
conn = psycopg2.connect("dbname='postgres' user='admin' host='ec2-3-144-245-96.us-east-2.compute.amazonaws.com' password='admin' port=5432")

In [29]:
## Importando as Query (resquest,response,geoapi)
sql_request = "select * from request;"
sql_response = "select * from response;"
sql_geoapi = "select * from geoapi;"

In [30]:
## Exportando as Query para o pandas
df_request = pd.read_sql_query(sql_request, conn)
df_response = pd.read_sql_query(sql_response, conn)
df_geoapi = pd.read_sql_query(sql_geoapi, conn)

In [31]:
## Juntando o dataframe request com o response
m = pd.merge(df_request, df_response , how = 'outer', on = 'request_id')

In [33]:
m.head(5)

   request_id                      full_address_request  ...    longitude geoapi_id
0           1                                      None  ...          NaN       NaN
1        5286  RUA COMENDADOR ARAUJO, 86, JOINVILLE, SC  ...     -48.8453       8.0
2        5286  RUA COMENDADOR ARAUJO, 86, JOINVILLE, SC  ...    -48.84536       2.0
3        5286  RUA COMENDADOR ARAUJO, 86, JOINVILLE, SC  ...   -48.845502       3.0
4        5286  RUA COMENDADOR ARAUJO, 86, JOINVILLE, SC  ...  -48.8453033      10.0

[5 rows x 22 columns]

## Ideias para análise


1.   Substituir o numero da geoapi_id pelo nome do provedor
2.   eliminar a coluna district_x